### ISSUE TITLE
codegen doesn't build on zig stable 0.13.0

### ISSUE THREAD

**Issue by robertgzr** [ianprime0509/zig-gobject#79]
it uses the new field names of `builtin.Type` introduced here: https://github.com/ziglang/zig/pull/21225

it actually fails earlier on:
```
/home/user/src/zig-gobject/build.zig:278:80: error: type '@TypeOf(.enum_literal)' not a function
    const gir_fixes_profiles: std.EnumArray(GirProfile, []const []const u8) = .init(.{
                                                                              ~^~~~
referenced by:
    runBuild__anon_8819: /opt/zig-bin-0.13.0/lib/std/Build.zig:2116:27
    main: /opt/zig-bin-0.13.0/lib/compiler/build_runner.zig:301:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

which can be fixed by not relying on the receiver to be inferred (couldn't find the relevant change in the zig repo for that :p)
<details>
<summary>patch</summary>

```diff
diff --git a/build.zig b/build.zig
index c0829c9..190357d 100644
--- a/build.zig
+++ b/build.zig
@@ -275,14 +275,14 @@ pub fn build(b: *std.Build) void {
         "freetype2-2.0",
         "GObject-2.0",
     };
-    const gir_fixes_profiles: std.EnumArray(GirProfile, []const []const u8) = .init(.{
+    const gir_fixes_profiles = std.EnumArray(GirProfile, []const []const u8).init(.{
         .gnome46 = &.{
             "AppStream-1.0",
         },
         .gnome47 = &.{},
     });
     const gir_fixes: []const []const u8 = b.option([]const []const u8, "gir-fixes", "GIR fixes to apply") orelse gir_fixes: {
-        var applicable_fixes: std.ArrayList([]const u8) = .init(b.allocator);
+        var applicable_fixes = std.ArrayList([]const u8).init(b.allocator);
         defer applicable_fixes.deinit();
         for (gir_fixes_common) |fix| {
             applicable_fixes.append(b.fmt("{0s}=gir-fixes/common/{0s}.xslt", .{fix})) catch @panic("OOM");

```

</details>

Not sure what you think about this. I don't think this is a huge deal as it only impacts ppl that want to generate the bindings from scratch. It makes sense to document that though.

**Comment by ianprime0509** [comment]
Right now, the binding generator only officially supports Zig master, while the bindings themselves target both 0.13.0 and master:

> The generated bindings are tested on Zig 0.13.0 and master, though support for the latest master may temporarily regress when breaking changes are made upstream. The binding generator itself targets only the latest Zig master.

(from https://github.com/ianprime0509/zig-gobject?tab=readme-ov-file#usage)

However, it may be reasonable to support 0.13.0 as well for the bindings generator, if the changes involved aren't too considerable. Since there's already a compatibility wrapper for `@Type` in the project, it probably makes sense to use it for the binding generator as well.
